import { StyleSheet } from 'react-native';
import { pallete } from '../../configs/Colors';
import { Size, moderateSize } from '../../utils/useResponsiveness';
import { shadowStyles } from '../../configs/GlobalStyles';

export const styles = StyleSheet.create({
  screenContainer: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: pallete.screen,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Size.calcWidth(20),
    paddingTop: Size.calcHeight(60),
    paddingBottom: Size.calcHeight(20),
    backgroundColor: pallete.light,
    borderBottomLeftRadius: moderateSize(24),
    borderBottomRightRadius: moderateSize(24),
    ...shadowStyles,
    shadowColor: pallete.dark,
    shadowOpacity: 0.1,
  },
  appTitle: {
    fontSize: moderateSize(28),
    fontWeight: '700',
    color: pallete.text,
  },
  backButton: {
    width: moderateSize(40),
    height: moderateSize(40),
    borderRadius: moderateSize(20),
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileButton: {
    width: moderateSize(40),
    height: moderateSize(40),
    borderRadius: moderateSize(20),
    backgroundColor: pallete.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageTitle: {
    fontSize: moderateSize(18),
    fontWeight: '600',
    color: pallete.text,
    paddingHorizontal: Size.calcWidth(20),
    paddingTop: Size.calcHeight(24),
    paddingBottom: Size.calcHeight(16),
  },
  formSection: {
    paddingHorizontal: Size.calcWidth(20),
    marginBottom: Size.calcHeight(24),
  },
  sectionLabel: {
    fontSize: moderateSize(14),
    fontWeight: '500',
    color: pallete.text,
    marginBottom: Size.calcHeight(8),
  },
  sectionHelper: {
    fontSize: moderateSize(12),
    fontWeight: '400',
    color: pallete.grey,
    marginBottom: Size.calcHeight(12),
    fontStyle: 'italic',
  },
  inputField: {
    backgroundColor: pallete.light,
    borderRadius: moderateSize(12),
    paddingHorizontal: Size.calcWidth(16),
    paddingVertical: Size.calcHeight(16),
    fontSize: moderateSize(16),
    color: pallete.text,
    ...shadowStyles,
    shadowOpacity: 0.05,
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  timeOptionsContainer: {
    gap: Size.calcHeight(12),
  },
  timeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: pallete.light,
    borderRadius: moderateSize(12),
    paddingHorizontal: Size.calcWidth(16),
    paddingVertical: Size.calcHeight(16),
    ...shadowStyles,
    shadowOpacity: 0.05,
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  timeOptionSelected: {
    borderColor: pallete.primary,
    backgroundColor: '#F0F2FD',
  },
  timeText: {
    fontSize: moderateSize(16),
    fontWeight: '500',
    color: pallete.text,
  },
  radioButton: {
    width: moderateSize(20),
    height: moderateSize(20),
    borderRadius: moderateSize(10),
    borderWidth: 2,
    borderColor: '#E5E5E5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonSelected: {
    borderColor: pallete.primary,
  },
  radioButtonInner: {
    width: moderateSize(10),
    height: moderateSize(10),
    borderRadius: moderateSize(5),
    backgroundColor: pallete.primary,
  },
  frequencyContainer: {
    flexDirection: 'row',
    gap: Size.calcWidth(12),
  },
  frequencyButton: {
    flex: 1,
    backgroundColor: pallete.light,
    borderRadius: moderateSize(12),
    paddingVertical: Size.calcHeight(16),
    alignItems: 'center',
    justifyContent: 'center',
    ...shadowStyles,
    shadowOpacity: 0.05,
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  frequencyButtonSelected: {
    backgroundColor: pallete.primary,
    borderColor: pallete.primary,
  },
  frequencyText: {
    fontSize: moderateSize(16),
    fontWeight: '600',
    color: pallete.text,
  },
  frequencyTextSelected: {
    color: pallete.light,
  },
  doneButton: {
    backgroundColor: pallete.primary,
    borderRadius: moderateSize(16),
    paddingVertical: Size.calcHeight(18),
    marginHorizontal: Size.calcWidth(20),
    marginBottom: Size.calcHeight(30),
    alignItems: 'center',
    justifyContent: 'center',
    ...shadowStyles,
    shadowColor: pallete.primary,
    shadowOpacity: 0.3,
  },
  doneButtonText: {
    fontSize: moderateSize(18),
    fontWeight: '600',
    color: pallete.light,
  },
});
