import { StyleSheet } from 'react-native';
import { pallete } from '../../configs/Colors';
import { Size, moderateSize } from '../../utils/useResponsiveness';
import { shadowStyles } from '../../configs/GlobalStyles';

export const styles = StyleSheet.create({
  screenContainer: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: pallete.screen,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Size.calcWidth(20),
    paddingTop: Size.calcHeight(60),
    paddingBottom: Size.calcHeight(20),
    backgroundColor: pallete.light,
    borderBottomLeftRadius: moderateSize(24),
    borderBottomRightRadius: moderateSize(24),
    ...shadowStyles,
    shadowColor: pallete.dark,
    shadowOpacity: 0.1,
  },
  backButton: {
    width: moderateSize(40),
    height: moderateSize(40),
    borderRadius: moderateSize(20),
    backgroundColor: pallete.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: moderateSize(28),
    fontWeight: '700',
    color: pallete.text,
  },
  headerSpacer: {
    width: moderateSize(40),
  },
  avatarSection: {
    alignItems: 'center',
    paddingVertical: Size.calcHeight(40),
    paddingHorizontal: Size.calcWidth(20),
  },
  avatarContainer: {
    width: moderateSize(120),
    height: moderateSize(120),
    borderRadius: moderateSize(60),
    backgroundColor: pallete.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Size.calcHeight(20),
    ...shadowStyles,
    shadowColor: pallete.primary,
    shadowOpacity: 0.2,
  },
  userName: {
    fontSize: moderateSize(24),
    fontWeight: '700',
    color: pallete.text,
    textAlign: 'center',
    marginBottom: Size.calcHeight(8),
  },
  userRole: {
    fontSize: moderateSize(16),
    fontWeight: '400',
    color: pallete.grey,
    textAlign: 'center',
  },
  infoSection: {
    paddingHorizontal: Size.calcWidth(20),
    marginBottom: Size.calcHeight(30),
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: pallete.light,
    borderRadius: moderateSize(16),
    padding: Size.calcWidth(20),
    marginBottom: Size.calcHeight(12),
    ...shadowStyles,
    shadowColor: pallete.dark,
    shadowOpacity: 0.05,
  },
  infoIconContainer: {
    width: moderateSize(48),
    height: moderateSize(48),
    borderRadius: moderateSize(24),
    backgroundColor: pallete.screen,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Size.calcWidth(16),
  },
  infoContent: {
    flex: 1,
  },
  infoTitle: {
    fontSize: moderateSize(16),
    fontWeight: '600',
    color: pallete.text,
    marginBottom: Size.calcHeight(4),
  },
  infoSubtitle: {
    fontSize: moderateSize(14),
    fontWeight: '400',
    color: pallete.grey,
  },
  settingsSection: {
    paddingHorizontal: Size.calcWidth(20),
    marginBottom: Size.calcHeight(30),
  },
  settingsItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: pallete.light,
    borderRadius: moderateSize(16),
    paddingVertical: Size.calcHeight(18),
    paddingHorizontal: Size.calcWidth(20),
    marginBottom: Size.calcHeight(8),
    ...shadowStyles,
    shadowColor: pallete.dark,
    shadowOpacity: 0.05,
  },
  settingsIconContainer: {
    width: moderateSize(32),
    height: moderateSize(32),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Size.calcWidth(16),
  },
  settingsText: {
    flex: 1,
    fontSize: moderateSize(16),
    fontWeight: '500',
    color: pallete.text,
  },
  logoutButton: {
    flexDirection: 'row',
    backgroundColor: pallete.primary,
    borderRadius: moderateSize(16),
    paddingVertical: Size.calcHeight(18),
    paddingHorizontal: Size.calcWidth(30),
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: Size.calcWidth(20),
    marginBottom: Size.calcHeight(40),
    ...shadowStyles,
    shadowColor: pallete.primary,
    shadowOpacity: 0.3,
  },
  logoutIcon: {
    marginRight: Size.calcWidth(8),
  },
  logoutButtonText: {
    fontSize: moderateSize(16),
    fontWeight: '600',
    color: pallete.light,
  },
});